### ISSUE TITLE
Seablock unplayable with Momostweak enabled.

### ISSUE THREAD

**Issue by ChrisJStone** [Archemide/MomosTweak#6]
When starting a new sea block game with MomosTweak enabled you are unable to craft an electrolyser due to the recipe requiring basic structure components which is locked behind steel processing

**Comment by domis86** [comment]
Ok. I will check it and try to fix.
Thanks for report 👍

**Comment by ChrisJStone** [comment]
Your welcome. I took another look and the Crystalilizer is uncraftable for the same reason. As a quick fix so I can continue testing I cheated in 5 of the basic structure components. After unlocking "green science" 3 more structure components will be required to craft a Filtration unit. Also Alginic acid is uncraftable by hand which locks progression at Basic circuit board.

**Comment by domis86** [comment]
Mod updated to version 1.1.6 : https://mods.factorio.com/mod/MomosTweak

@ChrisJStone all problems which you mentioned should be gone now. Please confirm if you can.

Thanks for reporting 👍
